env: "kitchen-complete-v0"
seed: 0
n_epochs: 10
feedback_type: [
    # "comparative",
    # "attribute",
    # "evaluative",
    "keypoint",
    # "visual"
]
num_query: 25
len_query: 100
fake_label: false
relabel_human_labels: false 
use_wandb: false
save_model: false
