# environment
# domain: mujoco
# env: hopper-medium-v2
domain: d4rl
env: kitchen-mixed-v0
fake_label: false
modality: 'state'  # state/pixel
structure: 'mlp' # mlp/transformer1/transformer2/transformer3
clip_action: 0.999  # only d4rl
stack: false  # stack frame in pixel benchmark, only atari

# feedback type
feedback_type: ['attribute']

# learning
ensemble_size: 1
batch_size: 64
n_epochs: 100
# num_query: 5 # original 2000
# len_query: 200
data_dir: "../crowdsource_human_labels/"

# misc
seed: 888
exp_name: mlp
save_model: true
use_wandb: false
wandb_project: Uni-RLHF
wandb_entity: xiguapi
device: "cpu"


# transformer structure
d_model: 256
nhead: 4
num_layers: 1
max_seq_len: 200

# attribute strength mapping
attr_map_ensemble_size: 1 # original 3
attr_map_n_gradient_steps: 2 # original 3000
attr_map_batch_size: 4 # original 256
attr_map_test_size: 0.2
attr_map_test_interval: 1 # original 100
attr_map_target: [1, 1] # the desired target attributes
attr_map_load: False # load the attribute mapping if it already exists
attr_map_n_pseudo_labels: 10 # number of generated pseudo labels
attr_map_threshold: 0.1 # threshold to determine when trajectories have equal preference