# environment
domain: d4rl
env: kitchen-mixed-v0
fake_label: false
modality: 'state'  # state/pixel
structure: 'mlp' # mlp/transformer1/transformer2/transformer3
clip_action: 0.999  # only d4rl
stack: false  # stack frame in pixel benchmark, only atari

# feedback type
feedback_type: ['comparative']

# learning
ensemble_size: 1
batch_size: 64
n_epochs: 100
num_query: 5 # original 2000
len_query: 200
data_dir: "../crowdsource_human_labels/"

# misc
seed: 888
exp_name: mlp
save_model: true
use_wandb: false
wandb_project: Uni-RLHF
wandb_entity: xiguapi


# transformer structure
d_model: 256
nhead: 4
num_layers: 1
max_seq_len: 200